# Generated by Django 4.1.2 on 2023-06-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0002_remove_comment_commentparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
