# Generated by Django 4.1.2 on 2023-06-10 16:49

import Entity.models.User
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entity', '0004_remove_book_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(max_length=254, unique=True, validators=[Entity.models.User.validate_length_not_zero]),
        ),
        migrations.AlterField(
            model_name='user',
            name='Password',
            field=models.CharField(max_length=255, validators=[Entity.models.User.validate_length_not_zero]),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.CharField(max_length=225, validators=[Entity.models.User.validate_length_not_zero]),
        ),
    ]
